include: ../analysis_options.yaml

analyzer:
  errors:
    invalid_use_of_internal_member: ignore

linter:
  rules:
    # Allow imports from src files of `widgetbook` package
    implementation_imports: false
