include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

  exclude:
    - "bricks"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/example/*.dart"
    - "**/example/**/*.dart"

linter:
  rules:
    public_member_api_docs: false

    # Constructors
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true

    # Imports
    prefer_relative_imports: true
    directives_ordering: true
