analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.book.dart"

formatter:
  trailing_commas: preserve

linter:
  rules:
    # Constructors
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true

    # Imports
    prefer_relative_imports: true
    directives_ordering: true
    combinators_ordering: true
    depend_on_referenced_packages: true
    avoid_web_libraries_in_flutter: true
    implementation_imports: true

    # Dependencies
    sort_pub_dependencies: true

    # Style
    prefer_single_quotes: true
    require_trailing_commas: true
    noop_primitive_operations: true
    use_super_parameters: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true

    # Types
    unrelated_type_equality_checks: true
    avoid_types_on_closure_parameters: true
    omit_local_variable_types: true

    # Docs
    comment_references: true
