include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "bricks"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/example/*.dart"
    - "**/example/**/*.dart"

linter:
  rules:
    public_member_api_docs: false
