name: widgetbook
repository: https://github.com/widgetbook/widgetbook

packages:
  - packages/**
  - examples/**
  - widgetbook_for_widgetbook/

command:
  version:
    branch: main

scripts:
  test-coverage:
    run: melos exec --dir-exists=test --flutter -- "flutter test --coverage && genhtml ./coverage/lcov.info --output-directory ./coverage/out"
    description: Run flutter test with coverage and generates coverage report

  generate:
    run: melos exec --depends-on="build_runner" -- "dart pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files.

  pana:
    run: melos exec -c 10 -- "../../tool/verify_pub_score.sh"
    select-package:
      no-private: true
    description: Checks if the package meets the pub.dev score requirement.