include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.widgetbook.dart"
linter:
  rules:
    public_member_api_docs: false