name: feature_preview
description: "An example project that previews Widgetbook features."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  widgetbook: ^3.13.1
  widgetbook_annotation: ^3.4.0

dev_dependencies: 
  build_runner: ^2.4.15
  widgetbook_generator: ^3.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
