name: feature_preview
description: "An example project that previews Widgetbook features."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  widgetbook: ^3.18.0
  widgetbook_annotation: ^3.8.0

dev_dependencies: 
  build_runner: ^2.6.0
  widgetbook_generator: ^3.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
