// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59_r0Uv1xurIq_sHbuw6_EpFa7HNTBiU',
    appId: '1:143120017981:web:422b680952252deb4b9854',
    messagingSenderId: '143120017981',
    projectId: 'widgetbook-cookbook',
    authDomain: 'widgetbook-cookbook.firebaseapp.com',
    storageBucket: 'widgetbook-cookbook.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4XUdoQT1aG7fe-TXbky8oREd-VunIW8',
    appId: '1:143120017981:android:7fd510e1925627244b9854',
    messagingSenderId: '143120017981',
    projectId: 'widgetbook-cookbook',
    storageBucket: 'widgetbook-cookbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfOV3Ov2MBkjjZq_DDfFLJZMRjCyXtxLc',
    appId: '1:143120017981:ios:5529e4161a501f464b9854',
    messagingSenderId: '143120017981',
    projectId: 'widgetbook-cookbook',
    storageBucket: 'widgetbook-cookbook.appspot.com',
    iosBundleId: 'com.example.cookbook1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfOV3Ov2MBkjjZq_DDfFLJZMRjCyXtxLc',
    appId: '1:143120017981:ios:5b5cfc22cf3afc654b9854',
    messagingSenderId: '143120017981',
    projectId: 'widgetbook-cookbook',
    storageBucket: 'widgetbook-cookbook.appspot.com',
    iosBundleId: 'com.example.cookbook1.RunnerTests',
  );
}
