/// Env variables for CI Vendors.
/// https://github.com/watson/ci-info/blob/master/vendors.json
final ciKeys = {
  // Defaults
  'CI',
  'CI_NAME',
  'CONTINUOUS_INTEGRATION',
  'TASK_ID',
  'RUN_ID',
  'BUILD_NUMBER',

  // Common Vendors
  'GITHUB_ACTIONS',
  'CM_BUILD_ID',
  'GITLAB_CI',
  'CIRCLECI',
  'CIRRUS_CI',

  // Vendors
  'AC_APPCIRCLE',
  'APPVEYOR',
  'CODEBUILD_BUILD_ARN',
  'SYSTEM_TEAMFOUNDATIONCOLLECTIONURI',
  'bamboo_planKey',
  'BITBUCKET_COMMIT',
  'BITRISE_IO',
  'BUDDY_WORKSPACE_ID',
  'BUILDKITE',
  'CF_BUILD_ID',
  'DRONE',
  'DSARI',
  'EAS_BUILD',
  'GERRIT_PROJECT',
  'GO_PIPELINE_LABEL',
  'BUILDER_OUTPUT',
  'HARNESS_BUILD_ID',
  'HUDSON_URL',
  'JENKINS_URL',
  'LAYERCI',
  'MAGNUM',
  'NETLIFY',
  'NEVERCODE',
  'RELEASE_BUILD_ID',
  'RENDER',
  'SAILCI',
  'SCREWDRIVER',
  'SEMAPHORE',
  'SHIPPABLE',
  'TDDIUM',
  'STRIDER',
  'TEAMCITY_VERSION',
  'TRAVIS',
  'NOW_BUILDER',
  'VERCEL',
  'APPCENTER_BUILD_ID',
  'CI_XCODE_PROJECT',
  'XCS',
};
