builders:
  story_builder:
    import: "package:widgetbook/src/generator/builder.dart"
    builder_factories: ["storyBuilder"]
    runs_before: [":components_builder"]
    build_extensions: { ".stories.dart": [".stories.book.dart"] }
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        - lib/**.stories.dart

  components_builder:
    import: "package:widgetbook/src/generator/builder.dart"
    builder_factories: ["componentsBuilder"]
    build_extensions: { ".stories.dart": [".dart"] }
    runs_before: [":telemetry"]
    auto_apply: dependents
    build_to: source

  telemetry:
    import: "package:widgetbook/src/generator/builder.dart"
    builder_factories: ["reportTelemetry"]
    build_extensions: { ".book.dart": [".track"] }
    required_inputs: [".book.dart"]
    auto_apply: root_package
    build_to: cache
    defaults:
      options:
        debug: false
      generate_for:
        - lib/components.book.dart
