import 'addons_configs.dart';
import 'use_case_metadata.dart';

/// Parsed representation of the cache files that were generated by the
/// `widgetbook_generator` package.
class CacheStore {
  const CacheStore({
    required this.addonsConfigs,
    required this.useCases,
  });

  const CacheStore.empty() : addonsConfigs = null, useCases = const [];

  final AddonsConfigs? addonsConfigs;
  final List<UseCaseMetadata> useCases;

  /// Returns `true` if the cache store doesn't have any use-cases.
  /// The [addonsConfigs] is not considered, because it is optional.
  bool get isEmpty => useCases.isEmpty;
}
