import 'dart:convert';

import 'package:file/file.dart';
import 'package:file/local.dart';
import 'package:path/path.dart';

import 'cache.dart';

/// Reads the files generated by `widgetbook_test` package in the
/// `build/.widgetbook` directory.
class CacheReader {
  const CacheReader({
    this.fileSystem = const LocalFileSystem(),
  });

  final FileSystem fileSystem;

  Future<CacheStore> read(String projectPath) async {
    final generatedDir = join(projectPath, 'build', '.widgetbook');
    final generatedDirExist = await fileSystem.isDirectory(generatedDir);

    if (!generatedDirExist) {
      return const CacheStore.empty();
    }

    final cacheFiles = await fileSystem
        .directory(generatedDir)
        .list(recursive: true)
        .where((entity) => entity is File && entity.path.endsWith('.json'))
        .cast<File>()
        .toList();

    final scenarios = <ScenarioRecord>[];

    for (final jsonFile in cacheFiles) {
      final jsonContent = await jsonFile.readAsString();
      final data = jsonDecode(jsonContent) as Map<String, dynamic>;
      final scenario = ScenarioRecord.fromJson(data);
      scenarios.add(scenario);
    }

    return CacheStore(
      scenarios: scenarios,
    );
  }
}
