import 'cache.dart';

/// Parsed representation of the cache files that were generated by the
/// `widgetbook_test` package.
class CacheStore {
  const CacheStore({
    required this.scenarios,
  });

  const CacheStore.empty() : scenarios = const [];

  final List<ScenarioRecord> scenarios;

  int get totalSnapshotSize => scenarios.fold(
    0,
    (sum, snapshot) => sum + snapshot.image.size,
  );

  /// Returns `true` if the [CacheStore] doesn't have any [stories] or [scenarios].
  bool get isEmpty => scenarios.isEmpty;
}
